# DataSource (prod - RDS)
spring.datasource.url=jdbc:mysql://${DB_URL}:3306/benly?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=admin
spring.datasource.password=${DB_PASSWORD}

# JPA (prod)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Swagger OFF (prod)
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# OAuth redirect (prod)
kakao.redirect-uri=https://devoir-seven.vercel.app/oauth/callback/kakao